name: mldonkey
description: MLdonkey client for dart using GuiProtocol.
version: 0.0.1
homepage: https://github.com/reimashi/dart-mldonkey
author: Aitor González Fernández <reimashi@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  logging: ^0.11.3
  size_type:
    git: https://github.com/minerhub/dart-size-type.git

dev_dependencies:
  test: ^0.12.0
