name: mldonkey
description: MLdonkey client for dart using GuiProtocol.
version: 0.0.1
homepage: https://github.com/reimashi/dart-mldonkey
author: Aitor González Fernández <reimashi@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: ^0.11.3
  size_type:
    git: https://github.com/TokkennoDart/dart-size-type.git

dev_dependencies:
  test: ^1.3.2
